<a href="https://colab.research.google.com/github/divyasaminathan02/Sridivyadharshini-Codeboosters-Internship-2026/blob/main/Phase_01_Data_Engineering/Day_04_Machine_Learning_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd
a=pd.read_csv("/content/SOCR-HeightWeight.csv")

In [55]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [56]:
x=a[['Height(Inches)']]
y=a[['Weight(Pounds)']]

In [57]:
a.isnull().any()
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
#splits the data for training and testing - 4 components
#test_size -> the percentage of data to be used for testing

In [60]:
x_train

       Height(Inches)
23112        66.27796
155          64.12642
13297        67.41853
17008        67.20212
291          66.80598
...               ...
14243        71.29561
20966        73.47464
2380         68.48099
15779        65.74710
18215        67.69354

[20000 rows x 1 columns]

In [61]:
#select and import model----
from sklearn.linear_model import LinearRegression
model=LinearRegression()

#to train the model
model.fit(x_train,y_train)

LinearRegression()

In [62]:
#to test the data - the output in the model predicted value
model.predict(x_test)

array([[116.96826226],
       [139.1995419 ],
       [127.79295382],
       ...,
       [120.16965874],
       [140.47111286],
       [128.92667573]])

In [63]:
y_pred=model.predict(x_test)

In [64]:
# we use this to minus the prdeicted answer with y test
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [65]:
mean_absolute_error(y_test,y_pred)

7.975660516987686

In [66]:
mean_squared_error(y_test,y_pred)

100.36889467812104

In [67]:
r2_score(y_test,y_pred)

0.2593976455823833

In [68]:
import joblib

In [69]:
joblib.dump(model,"linear.pkl")

['linear.pkl']

In [70]:
!pip install pyspark --quiet
print("PySpark installation complete!")

PySpark installation complete!

In [71]:
from pyspark.sql import SparkSession

from pyspark.sql import functions as F

from pyspark.sql.functions import year, month, to_date, col, round as spark_round

import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

spark=SparkSession.builder \
  .appName('Day4_BigData_Sales') \
  .config('Spark.sql.adaptive.enabled', 'true') \
  .getOrCreate()

print(f"Spark version : {spark.version}")
print(f"SparkSession : ACTIVE")
print(f"Application : {spark.sparkContext.appName}")

Spark version : 4.0.2
SparkSession : ACTIVE
Application : Day4_BigData_Sales

# BIG DATA AND PySPARK

In [72]:
df_bronze =spark.read \
   .option('header','true') \
   .option('inferSchema','true') \
   .csv("large_sales_data.csv")

print("=== BRONZE LAYER -Raw Data ===")
print(f'Rows : {df_bronze.count()}')

print(f'Columns : {len(df_bronze.columns)}')
print(f"Names : {df_bronze.columns}")
print()
df_bronze.printSchema()

=== BRONZE LAYER -Raw Data ===
Rows : 5000
Columns : 13
Names : ['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'revenue', 'order_date', 'city', 'region', 'sales_rep', 'payment_method', 'order_status']

root
 |-- order_id: integer (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- product: string (nullable = true)
 |-- category: string (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- revenue: integer (nullable = true)
 |-- order_date: date (nullable = true)
 |-- city: string (nullable = true)
 |-- region: string (nullable = true)
 |-- sales_rep: string (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- order_status: string (nullable = true)

In [73]:
print("First 5 rows")
df_bronze.show(5,truncate=False)

print('\nBasic statistics for numerical columns')
df_bronze.select('quantity','unit_price','revenue').describe().show()

First 5 rows
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|order_id|customer_name|product   |category   |quantity|unit_price|revenue|order_date|city     |region|sales_rep  |payment_method  |order_status|
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|1001    |Sneha Reddy  |Monitor   |Electronics|12      |22000     |264000 |2023-05-21|Mumbai   |West  |Meera Patel|UPI             |Delivered   |
|1002    |Ramesh Kumar |Printer   |Electronics|10      |12000     |120000 |2023-08-05|Delhi    |North |Anil Sharma|Credit Card     |Shipped     |
|1003    |Rahul Mishra |Mouse     |Accessories|10      |800       |8000   |2023-01-14|Ahmedabad|West  |Meera Patel|Cash on Delivery|Shipped     |
|1004    |Suresh Rao   |Tablet    |Electronics|5       |32000     |160000 |2023-01-04|Surat    |West  |Ravi Kumar |Cash on Delivery|Processing  |
|1005    |Priya Patel  |Headphones|Electronics|4       |3500      |14000  |2023-06-22|Bangalore|South |Sunita Rao |Cash on Delivery|Delivered   |
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
only showing top 5 rows

Basic statistics for numerical columns
+-------+-----------------+------------------+------------------+
|summary|         quantity|        unit_price|           revenue|
+-------+-----------------+------------------+------------------+
|  count|             5000|              5000|              5000|
|   mean|           7.9536|          12496.86|          99169.52|
| stddev|4.275313169878912|14857.384309295603|145972.97195261103|
|    min|                1|               600|               600|
|    max|               15|             45000|            675000|
+-------+-----------------+------------------+------------------+

In [74]:
df_bronze.write \
  .mode('overwrite') \
  .parquet('sales_bronze.parquet')

print('Bronze Parquet saved: sales_bronze.parquet')
import os

Bronze Parquet saved: sales_bronze.parquet

In [75]:
import pandas as pd
b=pd.read_csv("/content/data.csv")

In [76]:
b.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [77]:
X = b[['bedrooms', 'bathrooms', 'sqft_living', 'floors']]
Y = b[['price']]

In [78]:
b.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [79]:
b.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [82]:
x_train

      bedrooms  bathrooms  sqft_living  floors
2583       2.0       1.00          890     1.0
3227       3.0       2.50         1930     2.0
3436       5.0       2.00         2080     1.0
3166       3.0       2.50         3310     2.0
3196       3.0       2.00         1230     1.0
...        ...        ...          ...     ...
4367       3.0       1.75         1890     1.0
1576       2.0       1.00         1320     1.5
498        3.0       2.50         1040     2.0
1272       3.0       3.50         4080     1.5
2065       4.0       3.00         2720     2.0

[3680 rows x 4 columns]

In [83]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [84]:
model.predict(x_test)

array([[ 402570.19946648],
       [ 380092.12178488],
       [ 487478.43556518],
       [ 745118.04256291],
       [ 423230.3018148 ],
       [ 597361.03788835],
       [ 834824.29893292],
       [ 356528.61827691],
       [ 538183.59449977],
       [ 795705.28846146],
       [ 453944.83787831],
       [ 201881.47840956],
       [ 418432.28154349],
       [ 580103.99912991],
       [ 873418.28375156],
       [ 293153.35455053],
       [ 281642.38036808],
       [ 624384.78027893],
       [ 692516.79501896],
       [ 628041.66892884],
       [ 222616.75503856],
       [1350495.56555262],
       [ 712660.7054468 ],
       [ 588813.57915368],
       [ 497693.52107177],
       [ 809094.97572049],
       [ 354903.73026035],
       [ 407489.07176923],
       [ 402495.0251858 ],
       [ 539478.01367793],
       [ 479606.35104469],
       [ 528645.35270506],
       [ 402334.3733944 ],
       [ 815985.11091328],
       [ 676477.5316603 ],
       [ 558724.31431435],
       [1065034.52042098],
       [ 281794.19842714],
       [ 332456.61860636],
       [ 649573.17180346],
       [ 536364.14966879],
       [ 611131.00504388],
       [ 224800.57373096],
       [ 391407.06965521],
       [ 558013.56557945],
       [ 755182.77950815],
       [ 446581.2495204 ],
       [ 521196.28683643],
       [ 481384.52661802],
       [1234696.23556393],
       [ 460952.88610713],
       [ 510668.73147939],
       [ 374539.14452561],
       [ 623843.84859104],
       [ 669554.96094219],
       [ 389976.73845306],
       [ 513207.75877761],
       [ 950048.79221069],
       [ 681396.40396305],
       [ 424103.1718388 ],
       [ 351188.19682001],
       [ 451575.29610383],
       [ 574085.26446342],
       [ 744771.66768943],
       [ 798126.40272364],
       [ 374419.76199186],
       [ 451607.73162914],
       [ 477304.61931625],
       [ 397340.32681097],
       [ 302074.02087896],
       [ 709240.85510703],
       [ 837549.04931322],
       [ 481893.0227806 ],
       [ 494790.11991213],
       [ 672290.01455254],
       [ 267863.5794802 ],
       [ 492367.00697554],
       [ 678027.24539618],
       [ 281794.19842714],
       [ 860705.4402044 ],
       [ 374267.94393281],
       [ 757636.32929564],
       [ 419346.42082516],
       [ 311840.72451111],
       [ 312517.56822299],
       [ 503981.98683336],
       [ 255913.05715565],
       [ 496824.11921987],
       [ 362622.52722408],
       [ 412938.57252983],
       [ 681937.33565095],
       [ 484152.01575368],
       [ 444008.31719916],
       [ 676250.53932057],
       [ 349606.04755881],
       [ 701979.86253299],
       [ 350916.99622721],
       [ 248194.26019193],
       [1038849.74303139],
       [ 638045.66813077],
       [ 466893.50749754],
       [ 761309.12398062],
       [ 616125.05162731],
       [ 696037.77164488],
       [ 839970.1635754 ],
       [ 444719.06593406],
       [ 905995.00340141],
       [1014404.53576707],
       [ 519724.68637663],
       [ 384213.2983443 ],
       [ 621540.64736489],
       [ 624232.96221987],
       [ 530539.97181672],
       [ 665399.87935975],
       [ 498039.89594525],
       [ 701692.13244995],
       [ 267863.5794802 ],
       [ 498750.64468015],
       [ 379567.09613206],
       [ 387132.60553902],
       [ 821011.59302203],
       [ 908085.64882519],
       [ 476119.27944179],
       [ 400268.46773803],
       [ 605985.14040139],
       [ 557776.27000967],
       [ 566003.56313598],
       [ 307371.7035805 ],
       [ 923675.0608117 ],
       [ 918766.491739  ],
       [ 311012.06274017],
       [ 290580.42222929],
       [ 603260.3900211 ],
       [ 518353.62342009],
       [ 459565.29366035],
       [ 932984.84076897],
       [ 279373.08416495],
       [ 446733.06757946],
       [ 437390.85209687],
       [ 472429.95526657],
       [ 535957.037052  ],
       [ 392549.67077431],
       [ 316749.29358381],
       [ 701420.93185715],
       [ 701031.81822831],
       [ 626416.78091228],
       [ 501967.98518796],
       [ 560663.14167907],
       [ 268929.53682092],
       [1149264.4433101 ],
       [ 432768.5436095 ],
       [ 484752.21568718],
       [ 413013.7468105 ],
       [ 510904.55755146],
       [ 937893.40984167],
       [ 551801.74359625],
       [ 958867.45153816],
       [ 520926.55574134],
       [ 827105.50196919],
       [ 796230.31411428],
       [ 395122.60309555],
       [ 658629.12670071],
       [ 517067.15725947],
       [ 279221.26610589],
       [ 289166.62051739],
       [ 688167.1566221 ],
       [ 682885.37995563],
       [ 830626.47859511],
       [ 532251.80684171],
       [ 490203.18594548],
       [ 458497.86682193],
       [ 398643.57972147],
       [ 487748.16666028],
       [ 498836.12219087],
       [ 410137.17837115],
       [ 451846.49669663],
       [ 449305.9999007 ],
       [ 201237.07022299],
       [ 357324.84452254],
       [ 421005.21386474],
       [ 388200.03237745],
       [ 484498.39062716],
       [ 624081.14416082],
       [ 414758.01736081],
       [ 364128.03270689],
       [ 276648.33378465],
       [ 412938.57252983],
       [ 634676.5095639 ],
       [1045279.72362198],
       [ 492742.21324371],
       [ 338550.52755353],
       [ 872589.62198062],
       [ 224800.57373096],
       [ 549617.92490384],
       [ 318730.8597039 ],
       [ 497888.07788619],
       [ 279221.26610589],
       [ 486530.3912605 ],
       [ 413133.12934425],
       [ 312517.56822299],
       [ 538140.85574441],
       [ 309869.46162107],
       [ 410213.82214953],
       [ 469060.7966997 ],
       [ 339466.1363329 ],
       [ 440369.4275372 ],
       [ 256064.87521471],
       [ 554374.67591749],
       [ 478659.77623772],
       [ 715114.2552343 ],
       [ 570912.13220868],
       [ 812903.68242946],
       [2245995.39587874],
       [ 479759.63860146],
       [ 590513.64145092],
       [ 701183.63628737],
       [ 371771.65538995],
       [ 652838.85387165],
       [ 562093.47288122],
       [ 256064.87521471],
       [ 595541.59305737],
       [ 310215.83649455],
       [ 566680.40684786],
       [ 503430.61595689],
       [ 383764.91646986],
       [ 578479.11111335],
       [ 263631.85411938],
       [ 383882.8295059 ],
       [ 600687.45769985],
       [ 494790.11991213],
       [ 348192.24584691],
       [ 742198.73536819],
       [ 708300.76381989],
       [ 281794.19842714],
       [ 506554.9191546 ],
       [ 597555.59470277],
       [ 383205.98579402],
       [ 401775.44271856],
       [ 429806.49765942],
       [ 707211.2046862 ],
       [ 685306.49421781],
       [ 379836.82722715],
       [ 608675.98575867],
       [ 456872.97880537],
       [ 734597.8514405 ],
       [ 320388.18324577],
       [ 633576.64720016],
       [ 724425.50468927],
       [ 345965.68839914],
       [ 573722.3600997 ],
       [ 404314.47001678],
       [ 657409.88180322],
       [ 562245.29094027],
       [ 621422.73432885],
       [ 299806.19417354],
       [1012627.82969145],
       [ 696275.06721466],
       [ 387251.98807276],
       [1039830.22286138],
       [ 353836.30342192],
       [ 373591.10022093],
       [ 335673.95911417],
       [ 801765.2923856 ],
       [ 294507.04197429],
       [ 691032.16791329],
       [ 296165.83501387],
       [ 304798.77125926],
       [ 618849.80200761],
       [ 636860.3282563 ],
       [ 398491.76166242],
       [ 248346.07825098],
       [ 855645.05307264],
       [ 370494.61174457],
       [ 704822.52594933],
       [ 487748.16666028],
       [ 467164.70809034],
       [ 656056.19437946],
       [ 765355.12625937],
       [ 401021.9552283 ],
       [ 390924.78275774],
       [ 322614.74069354],
       [ 811531.99601775],
       [ 643868.37648513],
       [ 502916.02949264],
       [ 338518.09202821],
       [ 527290.1957836 ],
       [ 451727.11416288],
       [ 587822.79609364],
       [ 725018.34038814],
       [ 900366.85186146],
       [ 712119.7737589 ],
       [ 531218.28502631],
       [ 302225.83893802],
       [ 915638.72036918],
       [ 575227.86558252],
       [ 297199.35682928],
       [ 600205.17080239],
       [ 798126.40272364],
       [ 453471.38471319],
       [ 530270.24072163],
       [ 636708.51019725],
       [ 508213.71219418],
       [ 232529.67392474],
       [ 528645.35270506],
       [ 644427.30716098],
       [ 316986.58915359],
       [ 637097.62382609],
       [ 737356.50684382],
       [ 355428.75591317],
       [ 420734.01327194],
       [ 381191.98414862],
       [ 551834.17912156],
       [ 347033.11523757],
       [ 367464.75574845],
       [ 425049.74664578],
       [ 519978.51143666],
       [ 332424.18308105],
       [ 581289.33900438],
       [1138776.68771301],
       [ 721767.09485731],
       [ 306457.56429884],
       [ 665162.58378997],
       [ 245773.14592974],
       [ 240432.72447284],
       [ 744483.93760639],
       [ 467012.89003128],
       [ 580255.81718897],
       [ 238054.34896601],
       [ 548323.50572568],
       [ 521196.28683643],
       [ 618967.71504364],
       [ 706177.68287079],
       [ 258139.61460342],
       [ 315242.31860329],
       [ 527697.30840038],
       [ 428570.7232717 ],
       [ 600687.45769985],
       [ 446429.43146134],
       [ 773902.58499404],
       [ 358949.7325391 ],
       [ 737052.8707257 ],
       [ 693464.83932364],
       [ 317663.43286547],
       [ 557099.42629779],
       [ 410560.197023  ],
       [ 444008.31719916],
       [1026440.53560234],
       [ 500612.82826649],
       [ 428570.7232717 ],
       [ 273923.58340435],
       [ 377112.07684685],
       [ 858132.50788316],
       [ 638146.79441693],
       [ 643072.15023951],
       [ 914374.11458678],
       [ 498987.94024993],
       [ 593120.47879518],
       [ 600839.27575891],
       [ 893747.91726147],
       [ 622099.57804073],
       [ 384830.87381058],
       [ 607847.32398774],
       [ 585401.68183145],
       [ 541627.92734731],
       [ 433445.38732139],
       [1310411.1352437 ],
       [ 584615.75881588],
       [ 827105.50196919],
       [ 557065.52127477],
       [ 784161.87875369],
       [ 296403.13058365],
       [ 673600.96322094],
       [ 401743.00719325],
       [ 810314.22061798],
       [ 560857.69849349],
       [ 401893.3557546 ],
       [ 485294.61687278],
       [ 724188.20911949],
       [ 835095.49952572],
       [ 406210.55862614],
       [ 468519.86501181],
       [ 504930.03113804],
       [ 616125.05162731],
       [ 397729.44043981],
       [ 557217.33933382],
       [ 289512.99539086],
       [ 551801.74359625],
       [ 456603.24771027],
       [ 639518.73808827],
       [ 797567.4720478 ],
       [ 371695.01161157],
       [ 624791.89289572],
       [ 333177.67057131],
       [ 570082.00094004],
       [ 503592.87320452],
       [ 425879.87791442],
       [ 452675.15846756],
       [ 504930.03113804],
       [ 321455.6100842 ],
       [ 433597.20538044],
       [ 418127.17592767],
       [ 405144.60128542],
       [ 506826.1197474 ],
       [ 711323.54751328],
       [ 443738.58610406],
       [ 385772.57055396],
       [ 346117.5064582 ],
       [ 531370.10308536],
       [ 622294.13485515],
       [ 673205.62333191],
       [ 395122.60309555],
       [1099955.71055464],
       [1112938.28519689],
       [ 647000.23948222],
       [ 639281.44251849],
       [ 798955.06449458],
       [ 390924.78275774],
       [ 418278.99398673],
       [ 291019.97037139],
       [ 747344.60001067],
       [ 732855.0503879 ],
       [ 324198.35945245],
       [ 292237.74577116],
       [ 541779.74540637],
       [ 926924.83684482],
       [ 430991.83753389],
       [ 371846.82967062],
       [ 487630.25362424],
       [ 500494.91523045],
       [ 755182.77950815],
       [ 490051.36788643],
       [ 431143.65559294],
       [ 737052.8707257 ],
       [ 240475.4632282 ],
       [ 266204.78644062],
       [ 487748.16666028],
       [ 425997.79095046],
       [ 544082.94663252],
       [ 513477.4898727 ],
       [1642048.20409118],
       [1083045.04666968],
       [ 601558.85822615],
       [ 271156.09426869],
       [ 293526.5621443 ],
       [ 704899.16972771],
       [ 387251.98807276],
       [ 325307.05554853],
       [ 780944.53824588],
       [ 314853.20497445],
       [ 721132.98990079],
       [ 407869.35166572],
       [ 383054.16773496],
       [ 836957.68311206],
       [ 329462.13713097],
       [ 607170.48027586],
       [ 765397.86501473],
       [ 337900.51656194],
       [ 885893.83172893],
       [ 791084.4494718 ],
       [ 315090.50054423],
       [ 604749.36601367],
       [ 372914.25650905],
       [ 691161.63809749],
       [ 559672.35861903],
       [ 479877.55163749],
       [ 373921.56905933],
       [ 850802.82454827],
       [ 270521.98931217],
       [ 544623.87832041],
       [ 487782.0716833 ],
       [ 303293.26577644],
       [ 500461.01020743],
       [ 469619.72737554],
       [ 444652.72538572],
       [ 373591.10022093],
       [ 608406.25466358],
       [ 549380.62933406],
       [ 518623.35451519],
       [ 474883.50505407],
       [ 261058.92179814],
       [ 381792.18408212],
       [ 312669.38628205],
       [ 574010.09018275],
       [ 644156.10656817],
       [ 383205.98579402],
       [ 474883.50505407],
       [ 559443.89678159],
       [ 523769.21915767],
       [ 552039.03916603],
       [ 798803.24643552],
       [ 775916.58663944],
       [ 324587.47308128],
       [ 266204.78644062],
       [ 428604.62829472],
       [ 809214.35825424],
       [ 410560.197023  ],
       [ 449154.18184164],
       [ 545150.37347094],
       [1145472.26609138],
       [ 248346.07825098],
       [ 443179.65542822],
       [ 240475.4632282 ],
       [ 980923.9800656 ],
       [ 602490.99649576],
       [ 422959.101222  ],
       [ 525665.30776703],
       [ 574958.13448743],
       [ 674473.83324495],
       [ 433564.76985513],
       [ 296251.3125246 ],
       [ 658088.19501281],
       [ 367259.89570398],
       [ 571588.97592056],
       [ 268734.9800065 ],
       [1339119.03389644],
       [ 756011.44127908],
       [ 594999.19187177],
       [ 333025.85251225],
       [ 430722.10643879],
       [ 369273.89734938],
       [ 646323.39577034],
       [ 658987.54621899],
       [ 346838.55842315],
       [ 749992.70661259],
       [ 531759.2167142 ],
       [ 475154.70564687],
       [ 456872.97880537],
       [ 531218.28502631],
       [ 584690.93309656],
       [1250437.4656095 ],
       [1345332.32537735],
       [ 382257.94148934],
       [ 564666.40520246],
       [ 430163.17576295],
       [ 589642.24092462],
       [ 528797.17076412],
       [ 653515.69758353],
       [ 592968.66073613],
       [ 358153.50629347],
       [ 408935.30900644],
       [ 286940.06306962],
       [ 641252.70540853],
       [ 683173.11003867],
       [ 353609.31108219],
       [ 822907.68163139],
       [ 564259.29258567],
       [ 268777.71876187],
       [1178632.65618449],
       [ 540561.9700066 ],
       [ 392549.67077431],
       [ 453428.64595783],
       [ 353609.31108219],
       [ 533943.03540661],
       [ 312171.19334951],
       [ 444956.36150384],
       [1489807.11849348],
       [ 536667.7857869 ],
       [ 814749.33652556],
       [ 857980.6898241 ],
       [ 289361.17733181],
       [ 410560.197023  ],
       [ 357527.09709485],
       [1203972.86576808],
       [ 540154.85738981],
       [ 370298.58543244],
       [ 469060.7966997 ],
       [ 510710.00073704],
       [ 545436.63405628],
       [ 397543.71735773],
       [ 657443.78682624],
       [ 359897.77684378],
       [ 850332.58229561],
       [ 659350.31462418],
       [ 672458.36210184],
       [ 532166.32933099],
       [ 680448.35965837],
       [ 672881.3807537 ],
       [ 279221.26610589],
       [ 329462.13713097],
       [ 455578.55962721],
       [ 606222.43597118],
       [ 680566.27269441],
       [ 533308.93045009],
       [ 506858.55527271],
       [ 356409.23574317],
       [ 831422.70484074],
       [ 433598.67487815],
       [ 748487.20112977],
       [ 373678.04722936],
       [ 325146.40375713],
       [ 488349.83609148],
       [ 267424.03133811],
       [ 332711.91316409],
       [ 329851.25075981],
       [ 446581.2495204 ],
       [ 391094.59980475],
       [ 405414.33238052],
       [ 941086.40380023],
       [ 885843.39721567],
       [ 383882.8295059 ],
       [ 875433.75489466],
       [ 658240.01307187],
       [ 695991.42875889],
       [ 457821.02311005],
       [ 576583.02250399],
       [ 687370.93037647],
       [ 602664.67493303],
       [ 561686.36026443],
       [ 353489.92854845],
       [ 987846.55078371],
       [ 247365.59842099],
       [ 763578.42018375],
       [ 323080.49810076],
       [ 315768.81375382],
       [ 709291.54687993],
       [ 422646.63137154],
       [ 548280.76697032],
       [ 560061.47224787],
       [ 556345.93880753],
       [ 770349.1728428 ],
       [ 776712.81288506],
       [ 796349.69664803],
       [ 415739.96668851],
       [ 497211.23417431],
       [ 402689.58200022],
       [ 467164.70809034],
       [ 867324.37480439],
       [ 421951.78867171],
       [ 604478.16542087],
       [ 817084.97327702],
       [ 796771.24580218],
       [ 505606.87484992],
       [ 541102.90169449],
       [ 232908.48432353],
       [ 438355.4258918 ],
       [ 802595.42365425],
       [ 474765.59201803],
       [ 235481.41664477],
       [ 281296.0054946 ],
       [ 494638.30185307],
       [ 311062.49725343],
       [ 317815.25092453],
       [ 307642.9041733 ],
       [1151294.97444574],
       [ 590547.54647394],
       [ 553848.18076696],
       [ 687776.57349555],
       [ 376164.03254217],
       [ 350874.25747184],
       [ 413929.35558987],
       [ 227762.61968104],
       [ 567585.71239718],
       [ 482450.48395874],
       [ 314413.65683235],
       [ 382215.20273397],
       [ 335945.15970697],
       [ 665551.69741881],
       [1090189.00692249],
       [ 334245.23336826],
       [ 348658.00325413],
       [ 546536.49642002],
       [ 230183.73394323],
       [ 690409.62010494],
       [ 459445.91112661],
       [ 383205.98579402],
       [ 510786.64451542],
       [ 298467.56674231],
       [ 402571.66896418],
       [ 256064.87521471],
       [ 500580.39274118],
       [ 549227.3417773 ],
       [1307957.5854562 ],
       [ 465709.63712078],
       [ 369122.07929032],
       [ 428215.51466588],
       [ 688167.1566221 ],
       [ 600128.52702401],
       [ 425728.05985536],
       [ 461749.11235276],
       [ 284367.13074838],
       [ 658434.56988629],
       [ 327803.34409139],
       [ 299306.5317433 ],
       [ 345288.84468726],
       [ 736645.75810892],
       [ 232908.48432353],
       [ 438185.60884479],
       [ 365195.45954532],
       [ 651738.99150792],
       [ 751542.42034848],
       [ 762782.19393813],
       [ 604208.43432578],
       [ 261058.92179814],
       [ 483355.78950806],
       [ 293678.38020335],
       [ 837397.23125416],
       [ 269488.46749677],
       [ 615448.20791543],
       [ 248194.26019193],
       [ 533791.21734755],
       [ 253340.12483441],
       [ 304798.77125926],
       [ 495349.05058797],
       [ 387284.42359808],
       [ 487748.16666028],
       [ 465539.82007378],
       [ 466022.10697124],
       [ 399997.26714523],
       [ 314176.36126257],
       [ 602897.6216159 ],
       [ 413133.12934425],
       [ 919731.06553392],
       [ 751374.07279918],
       [ 350131.07321163],
       [ 512259.71447293],
       [ 476508.39307063],
       [ 554374.67591749],
       [ 678221.8022106 ],
       [ 472158.75467377],
       [ 230183.73394323],
       [ 563912.9177122 ],
       [ 639704.46117035],
       [ 562245.29094027],
       [1219605.01650995],
       [ 462966.88775253],
       [ 441587.20293697],
       [ 374421.23148957],
       [ 439421.38323251],
       [ 605713.93980859],
       [ 959544.29525004],
       [ 951554.29769351],
       [ 383092.55760341],
       [ 654160.1057701 ],
       [ 367573.83505214],
       [1330962.15828832],
       [ 574958.13448743],
       [ 440726.10564072],
       [ 518471.53645613],
       [ 535957.037052  ],
       [ 786480.98601491],

In [85]:
y_pred=model.predict(x_test)

In [86]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [87]:
mean_absolute_error(y_test,y_pred)

176583.935747617

In [88]:
mean_squared_error(y_test,y_pred)

77212774627.40755

In [89]:
r2_score(y_test,y_pred)

0.49116136639012475

In [90]:
import joblib

In [92]:
joblib.dump(model,"multiple.pkl")

['multiple.pkl']